site_name: QuantaPy
site_description: Uncertainty-aware quantitative research framework

theme:
  name: readthedocs

nav:
  - Home: index.md
  - API:
      - Data: api/data.md
      - Calculator: api/calculator.md
      - Strategy: api/strategy.md
      - Simulation: api/simulation.md
      - Study: api/study.md
      - Registry: api/registry.md
